import 'controller/language_two_controller.dart';import 'package:flutter/material.dart';import 'package:yasir_s_application3/core/app_export.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_title.dart';import 'package:yasir_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:yasir_s_application3/widgets/custom_checkbox_button.dart';import 'package:yasir_s_application3/widgets/custom_text_form_field.dart';class LanguageTwoScreen extends GetWidget<LanguageTwoController> {const LanguageTwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 20.v), child: Padding(padding: EdgeInsets.symmetric(horizontal: 31.h), child: Column(children: [_buildSearchRow(), SizedBox(height: 32.v), Divider(), SizedBox(height: 17.v), _buildProfileList1(), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildProfileList()), SizedBox(height: 18.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildProfileList()), SizedBox(height: 20.v), _buildProfileList4(), SizedBox(height: 18.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildProfileList()), SizedBox(height: 19.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildProfileList()), SizedBox(height: 18.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildProfileList()), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildProfileList()), SizedBox(height: 18.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildProfileList()), SizedBox(height: 19.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildProfileList()), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildProfileList())])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 12.v, bottom: 12.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarTitle(text: "lbl_language".tr)); } 
/// Section Widget
Widget _buildSearchRow() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomTextFormField(controller: controller.enController, hintText: "lbl_en".tr, hintStyle: CustomTextStyles.bodyMedium15, textInputAction: TextInputAction.done, borderDecoration: TextFormFieldStyleHelper.fillOnPrimaryTL10, filled: true, fillColor: theme.colorScheme.onPrimary)), Container(height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 10.h, top: 8.v, bottom: 8.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCloseWhiteA70024x24, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgCloseWhiteA700, height: 6.adaptSize, width: 6.adaptSize, alignment: Alignment.center)]))]); } 
/// Section Widget
Widget _buildProfileList1() { return Padding(padding: EdgeInsets.only(left: 1.h), child: Column(children: [Obx(() => CustomCheckboxButton(width: 311.h, text: "lbl_english".tr, value: controller.english.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: theme.textTheme.titleSmall, isRightCheck: true, onChange: (value) {controller.english.value = value;})), SizedBox(height: 18.v), Divider()])); } 
/// Section Widget
Widget _buildProfileList4() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_japanese".tr, style: theme.textTheme.titleSmall), SizedBox(height: 19.v), Divider()]); } 
/// Common widget
Widget _buildProfileList() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_chinese".tr, style: theme.textTheme.titleSmall), SizedBox(height: 21.v), Divider()]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
