import 'controller/pro_profile_controller.dart';import 'package:flutter/material.dart';import 'package:yasir_s_application3/core/app_export.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:yasir_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:yasir_s_application3/widgets/custom_text_form_field.dart';class ProProfileScreen extends GetWidget<ProProfileController> {const ProProfileScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 32.h, vertical: 20.v), child: Column(children: [_buildTitle(), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_sarah".tr, style: CustomTextStyles.headlineLargeBold)), SizedBox(height: 2.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_wegan".tr, style: theme.textTheme.headlineLarge)), SizedBox(height: 22.v), Divider(), SizedBox(height: 17.v), _buildProfileList(), SizedBox(height: 19.v), _buildProfileList(), SizedBox(height: 19.v), _buildProfileList(), Spacer(), Divider(), SizedBox(height: 20.v), CustomTextFormField(controller: controller.signOutController, hintText: "lbl_sign_out".tr, hintStyle: CustomTextStyles.titleMediumRedA40001, textInputAction: TextInputAction.done), SizedBox(height: 23.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.fromLTRB(24.h, 12.v, 319.h, 12.v), onTap: () {onTapArrowLeft();})); } 
/// Section Widget
Widget _buildTitle() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 104.v, width: 113.h, margin: EdgeInsets.only(bottom: 3.v), child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.centerLeft, child: Container(height: 104.adaptSize, width: 104.adaptSize, decoration: AppDecoration.outlineOnPrimary3.copyWith(borderRadius: BorderRadiusStyle.circleBorder52), child: CustomImageView(imagePath: ImageConstant.imgEllipse30, height: 104.adaptSize, width: 104.adaptSize, alignment: Alignment.center))), Align(alignment: Alignment.bottomRight, child: Container(margin: EdgeInsets.only(bottom: 4.v), padding: EdgeInsets.symmetric(horizontal: 5.h), decoration: AppDecoration.fillRedA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_pro".tr, style: theme.textTheme.labelMedium))), CustomImageView(imagePath: ImageConstant.img5980x80, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(40.h), alignment: Alignment.centerLeft, margin: EdgeInsets.only(left: 12.h))])), Spacer(), SizedBox(height: 106.v, child: VerticalDivider(width: 1.h, thickness: 1.v, indent: 3.h)), Padding(padding: EdgeInsets.only(left: 22.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_joined".tr, style: theme.textTheme.bodySmall), SizedBox(height: 2.v), Text("lbl_2_mon_ago".tr, style: theme.textTheme.titleSmall), SizedBox(height: 11.v), Text("lbl_pro_member".tr, style: CustomTextStyles.bodySmallRedA40001), SizedBox(height: 2.v), Text("msg_until_18_jul_2022".tr, style: theme.textTheme.titleSmall), SizedBox(height: 1.v), Text("msg_12_months_subscription".tr, style: theme.textTheme.bodySmall)]))]); } 
/// Common widget
Widget _buildProfileList() { return Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("lbl_privacy_policy".tr, style: theme.textTheme.titleSmall)), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 24.adaptSize, width: 24.adaptSize)]), SizedBox(height: 17.v), Divider()]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
