import 'controller/fitness_instructors_controller.dart';import 'package:flutter/material.dart';import 'package:yasir_s_application3/core/app_export.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_title.dart';import 'package:yasir_s_application3/widgets/app_bar/custom_app_bar.dart';class FitnessInstructorsScreen extends GetWidget<FitnessInstructorsController> {const FitnessInstructorsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 13.v), child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [_buildTrainerOne(), SizedBox(height: 16.v), _buildTrainerTwo(), SizedBox(height: 16.v), _buildTrainerThree(), SizedBox(height: 16.v), _buildTrainerFour(), SizedBox(height: 16.v), _buildTrainerFive(), SizedBox(height: 16.v), _buildTrainerSix(), SizedBox(height: 16.v), _buildTrainerSeven()])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 12.v, bottom: 12.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarTitle(text: "msg_fitness_trainers".tr)); } 
/// Section Widget
Widget _buildTrainerOne() { return Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 13.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgImage1, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(32.h), margin: EdgeInsets.only(left: 7.h, top: 2.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("lbl_richard_will".tr, style: theme.textTheme.titleMedium), Container(width: 33.h, margin: EdgeInsets.only(left: 8.h, top: 3.v, bottom: 4.v), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 1.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_4_8".tr, style: CustomTextStyles.labelMediumOnError))]), SizedBox(height: 2.v), Text("msg_high_intensity_training".tr, style: theme.textTheme.bodySmall), SizedBox(height: 11.v), Text("msg_5_years_experience".tr, style: CustomTextStyles.bodySmallPrimary)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 24.v, bottom: 20.v))])); } 
/// Section Widget
Widget _buildTrainerTwo() { return Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 13.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgImage2, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(32.h), margin: EdgeInsets.only(left: 7.h, top: 2.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 14.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_jennifer_james".tr, style: theme.textTheme.titleMedium), Container(width: 33.h, margin: EdgeInsets.only(left: 8.h, top: 2.v, bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 1.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_4_6".tr, style: CustomTextStyles.labelMediumOnError))]), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("msg_functional_strength".tr, style: theme.textTheme.bodySmall)), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("msg_4_years_experience".tr, style: CustomTextStyles.bodySmallPrimary))])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 24.v, bottom: 20.v))])); } 
/// Section Widget
Widget _buildTrainerThree() { return Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 13.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgImage3, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(32.h), margin: EdgeInsets.only(left: 7.h, top: 2.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("lbl_brian_edward".tr, style: theme.textTheme.titleMedium), Container(width: 33.h, margin: EdgeInsets.only(left: 9.h, top: 3.v, bottom: 4.v), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 1.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_4_5".tr, style: CustomTextStyles.labelMediumOnError))]), SizedBox(height: 2.v), Text("msg_strength_training".tr, style: theme.textTheme.bodySmall), SizedBox(height: 11.v), Text("msg_6_years_experience".tr, style: CustomTextStyles.bodySmallPrimary)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 24.v, bottom: 20.v))])); } 
/// Section Widget
Widget _buildTrainerFour() { return Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 13.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgImage64x64, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(32.h), margin: EdgeInsets.only(left: 7.h, top: 2.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 136.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_emily_kevin".tr, style: theme.textTheme.titleMedium), Container(width: 33.h, margin: EdgeInsets.only(bottom: 6.v), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 1.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_4_9".tr, style: CustomTextStyles.labelMediumOnError))])), Text("msg_high_intensity_training".tr, style: theme.textTheme.bodySmall), SizedBox(height: 11.v), Text("msg_2_years_experience".tr, style: CustomTextStyles.bodySmallPrimary)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 24.v, bottom: 20.v))])); } 
/// Section Widget
Widget _buildTrainerFive() { return Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 13.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgImage4, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(32.h), margin: EdgeInsets.only(left: 7.h, top: 2.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("lbl_rebecca_smith".tr, style: theme.textTheme.titleMedium), Container(width: 33.h, margin: EdgeInsets.only(left: 9.h, top: 3.v, bottom: 4.v), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 1.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_4_8".tr, style: CustomTextStyles.labelMediumOnError))]), SizedBox(height: 2.v), Text("msg_functional_strength".tr, style: theme.textTheme.bodySmall), SizedBox(height: 11.v), Text("msg_8_years_experience".tr, style: CustomTextStyles.bodySmallPrimary)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 24.v, bottom: 20.v))])); } 
/// Section Widget
Widget _buildTrainerSix() { return Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 13.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgImage5, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(32.h), margin: EdgeInsets.only(left: 7.h, top: 2.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_ronald_jason".tr, style: theme.textTheme.titleMedium), Container(width: 33.h, margin: EdgeInsets.only(left: 9.h, top: 2.v, bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 1.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_4_2".tr, style: CustomTextStyles.labelMediumOnError))]), Text("msg_high_intensity_training".tr, style: theme.textTheme.bodySmall), SizedBox(height: 11.v), Text("msg_9_years_experience".tr, style: CustomTextStyles.bodySmallPrimary)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 24.v, bottom: 20.v))])); } 
/// Section Widget
Widget _buildTrainerSeven() { return Container(padding: EdgeInsets.symmetric(vertical: 12.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgImage6, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(32.h), margin: EdgeInsets.symmetric(vertical: 4.v)), Padding(padding: EdgeInsets.only(bottom: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("msg_cristofer_arcand".tr, style: theme.textTheme.titleMedium), Container(height: 17.v, width: 33.h, margin: EdgeInsets.only(left: 8.h, top: 5.v), child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.bottomCenter, child: Container(height: 16.v, width: 33.h, decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(4.h)))), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_4_8".tr, textAlign: TextAlign.center, style: CustomTextStyles.labelMediumOnError)))]))]), SizedBox(height: 2.v), SizedBox(width: 222.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 8.v), child: Text("msg_high_intensity_training".tr, style: theme.textTheme.bodySmall)), CustomImageView(imagePath: ImageConstant.imgDown, height: 24.adaptSize, width: 24.adaptSize)])), SizedBox(height: 5.v), Text("msg_7_years_experience".tr, style: CustomTextStyles.bodySmallPrimary)]))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
