import 'controller/video_controller.dart';import 'package:flutter/material.dart';import 'package:yasir_s_application3/core/app_export.dart';class VideoScreen extends GetWidget<VideoController> {const VideoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer, image: DecorationImage(image: AssetImage(ImageConstant.imgVideo), fit: BoxFit.cover)), child: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 32.v), CustomImageView(imagePath: ImageConstant.imgArrowLeftOnerror, height: 32.adaptSize, width: 32.adaptSize, margin: EdgeInsets.only(left: 24.h), onTap: () {onTapImgArrowLeft();}), Spacer(), _buildVideoPlayer()]))))); } 
/// Section Widget
Widget _buildVideoPlayer() { return Container(height: 242.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 32.v), decoration: AppDecoration.gradientOnPrimaryContainerToOnPrimaryContainer, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 19.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRefresh, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 1.v)), CustomImageView(imagePath: ImageConstant.imgRewind, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 30.h, top: 1.v)), CustomImageView(imagePath: ImageConstant.imgPlay, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 124.h, top: 1.v)), CustomImageView(imagePath: ImageConstant.imgVolume, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 30.h))]))), Align(alignment: Alignment.bottomCenter, child: SizedBox(height: 123.v, width: 327.h, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgLinkedin, height: 64.adaptSize, width: 64.adaptSize, alignment: Alignment.bottomCenter), Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Text("msg_lower_body_strength".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 7.v), Container(height: 10.v, width: 327.h, decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer, borderRadius: BorderRadius.circular(5.h)), child: ClipRRect(borderRadius: BorderRadius.circular(5.h), child: LinearProgressIndicator(value: 0.33, backgroundColor: theme.colorScheme.onErrorContainer, valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.primary)))), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_04_35".tr, style: theme.textTheme.bodyMedium), Text("lbl_15_00".tr, style: theme.textTheme.bodyMedium)]))]))])))])); } 

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); } 
 }
