import '../insight_page/widgets/days_item_widget.dart';import 'controller/insight_controller.dart';import 'models/days_item_model.dart';import 'models/insight_model.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:yasir_s_application3/core/app_export.dart';import 'package:yasir_s_application3/widgets/custom_checkbox_button.dart';
// ignore_for_file: must_be_immutable
class InsightPage extends StatelessWidget {InsightPage({Key? key}) : super(key: key);

InsightController controller = Get.put(InsightController(InsightModel().obs));

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, decoration: AppDecoration.fillOnErrorContainer, child: Column(children: [_buildDatePicker(), SizedBox(height: 26.v), Container(margin: EdgeInsets.symmetric(horizontal: 99.h), decoration: AppDecoration.outlineOnPrimary1.copyWith(borderRadius: BorderRadiusStyle.circleBorder84), child: Container(height: 168.adaptSize, width: 168.adaptSize, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 50.v), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgGroup284), fit: BoxFit.cover)), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_652".tr, style: CustomTextStyles.displaySmallWhiteA700))), Align(alignment: Alignment.bottomCenter, child: Container(height: 44.v, width: 104.h, margin: EdgeInsets.only(bottom: 9.v), child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.topRight, child: Text("lbl_cal".tr, style: theme.textTheme.headlineSmall)), Align(alignment: Alignment.bottomLeft, child: Text("lbl_active_calories".tr, style: theme.textTheme.bodyMedium))])))]))), SizedBox(height: 30.v), _buildNotification(), SizedBox(height: 30.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_finished_workout".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 13.v), _buildFinishedStack1(), SizedBox(height: 16.v), _buildFinishedStack2()])))); } 
/// Section Widget
Widget _buildDatePicker() { return SizedBox(height: 203.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.center, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 60.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.customBorderBL24), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeftGray800, height: 26.adaptSize, width: 26.adaptSize, margin: EdgeInsets.only(bottom: 57.v), onTap: () {onTapImgArrowLeft();}), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 56.v), child: Text("lbl_october_2021".tr, style: theme.textTheme.titleMedium)), CustomImageView(imagePath: ImageConstant.imgArrowRightGray800, height: 26.adaptSize, width: 26.adaptSize, margin: EdgeInsets.only(bottom: 57.v))]))), Align(alignment: Alignment.bottomRight, child: SizedBox(height: 203.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 24.h, top: 115.v, bottom: 24.v), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 14.h);}, itemCount: controller.insightModelObj.value.daysItemList.value.length, itemBuilder: (context, index) {DaysItemModel model = controller.insightModelObj.value.daysItemList.value[index]; return DaysItemWidget(model);}))))])); } 
/// Section Widget
Widget _buildNotification() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 93.adaptSize, width: 93.adaptSize, child: CircularProgressIndicator(value: 0.5)), Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.only(left: 22.h), shape: RoundedRectangleBorder(side: BorderSide(color: theme.colorScheme.onPrimary, width: 4.h), borderRadius: BorderRadiusStyle.roundedBorder46), child: Container(height: 93.adaptSize, width: 93.adaptSize, decoration: AppDecoration.outlineOnPrimary2.copyWith(borderRadius: BorderRadiusStyle.roundedBorder46), child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgNotificationRedA40001, height: 85.v, width: 46.h, alignment: Alignment.topRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 27.h, top: 13.v), child: Text("lbl_time".tr, style: theme.textTheme.bodyMedium))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 20.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_452".tr, style: CustomTextStyles.titleLargeOpenSans), Padding(padding: EdgeInsets.only(left: 5.h, top: 7.v, bottom: 4.v), child: Text("lbl_min".tr, style: theme.textTheme.bodyMedium))])))]))), Container(margin: EdgeInsets.only(left: 22.h), decoration: AppDecoration.outlineOnPrimary2.copyWith(borderRadius: BorderRadiusStyle.roundedBorder46), child: Container(width: 93.h, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 13.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup36), fit: BoxFit.cover)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 11.h), child: Text("lbl_heart".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 10.v), Align(alignment: Alignment.centerRight, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Text("lbl_72".tr, style: CustomTextStyles.titleLargeOpenSans), Padding(padding: EdgeInsets.only(left: 5.h, top: 9.v, bottom: 2.v), child: Text("lbl_bpm".tr, style: theme.textTheme.bodyMedium))])), SizedBox(height: 7.v)])))])); } 
/// Section Widget
Widget _buildFinishedStack1() { return Card(clipBehavior: Clip.antiAlias, elevation: 0, color: theme.colorScheme.onPrimary, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder12), child: Container(height: 73.v, width: 327.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_10_00".tr, style: CustomTextStyles.bodyMediumPrimary_1))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 2.v), child: Obx(() => CustomCheckboxButton(alignment: Alignment.topCenter, width: 295.h, text: "msg_stability_training2".tr, value: controller.stabilityTraining.value, isRightCheck: true, onChange: (value) {controller.stabilityTraining.value = value;}))))]))); } 
/// Section Widget
Widget _buildFinishedStack2() { return Card(clipBehavior: Clip.antiAlias, elevation: 0, color: theme.colorScheme.onPrimary, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder12), child: Container(height: 73.v, width: 327.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_25_00".tr, style: CustomTextStyles.bodyMediumPrimary_1))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 2.v), child: Obx(() => CustomCheckboxButton(alignment: Alignment.topCenter, width: 295.h, text: "lbl_flash_cycling".tr, value: controller.flashCycling.value, isRightCheck: true, onChange: (value) {controller.flashCycling.value = value;}))))]))); } 

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); } 
 }
