import '../payment_screen/widgets/paymentlist_item_widget.dart';import 'controller/payment_controller.dart';import 'models/paymentlist_item_model.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:yasir_s_application3/core/app_export.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_title.dart';import 'package:yasir_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:yasir_s_application3/widgets/custom_elevated_button.dart';class PaymentScreen extends GetWidget<PaymentController> {const PaymentScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_payment_method".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 11.v), _buildPaymentList(), SizedBox(height: 31.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_order_details".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 13.v), _buildOrderDetails(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildConfirmButton())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 12.v, bottom: 12.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarTitle(text: "lbl_payment".tr)); } 
/// Section Widget
Widget _buildPaymentList() { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 115.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 102.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 15.h);}, itemCount: controller.paymentModelObj.value.paymentlistItemList.value.length, itemBuilder: (context, index) {PaymentlistItemModel model = controller.paymentModelObj.value.paymentlistItemList.value[index]; return PaymentlistItemWidget(model);})))); } 
/// Section Widget
Widget _buildOrderDetails() { return Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(vertical: 13.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgDetails), fit: BoxFit.cover)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 61.v, width: 177.h, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_trainer".tr, style: theme.textTheme.bodySmall)), SizedBox(height: 7.v), Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_emily_kevin".tr, style: theme.textTheme.titleSmall), Container(height: 13.v, width: 27.h, margin: EdgeInsets.only(left: 17.h, bottom: 5.v), child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgPoint, height: 13.v, width: 27.h, alignment: Alignment.center), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_4_9".tr, style: theme.textTheme.labelSmall)))]))]), SizedBox(height: 1.v), Padding(padding: EdgeInsets.only(right: 11.h), child: Text("msg_high_intensity_training".tr, style: CustomTextStyles.bodySmallPrimary))])), CustomImageView(imagePath: ImageConstant.imgImage40x40, height: 40.adaptSize, width: 40.adaptSize, radius: BorderRadius.circular(20.h), alignment: Alignment.bottomLeft)])), SizedBox(height: 25.v), Text("lbl_date".tr, style: theme.textTheme.bodySmall), SizedBox(height: 2.v), Text("msg_20_october_2021".tr, style: theme.textTheme.titleSmall), SizedBox(height: 11.v), Text("lbl_time".tr, style: theme.textTheme.bodySmall), SizedBox(height: 1.v), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_09_30_am".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 29.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text("lbl_estimated_cost".tr, style: theme.textTheme.bodySmall)), Text("lbl_175_99".tr, style: theme.textTheme.titleSmall)])]))); } 
/// Section Widget
Widget _buildConfirmButton() { return CustomElevatedButton(text: "lbl_confirm".tr, margin: EdgeInsets.only(left: 56.h, right: 56.h, bottom: 32.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
