import 'controller/write_a_review_controller.dart';import 'package:flutter/material.dart';import 'package:yasir_s_application3/core/app_export.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_title.dart';import 'package:yasir_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:yasir_s_application3/widgets/custom_elevated_button.dart';import 'package:yasir_s_application3/widgets/custom_text_form_field.dart';class WriteAReviewScreen extends GetWidget<WriteAReviewController> {const WriteAReviewScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 62.h), child: Text("lbl_4_6".tr, style: CustomTextStyles.titleLargeOpenSansSemiBold))), SizedBox(height: 3.v), _buildRatingColumn(), SizedBox(height: 24.v), CustomTextFormField(controller: controller.reviewOptionalController, hintText: "msg_review_optional".tr, textInputAction: TextInputAction.done, maxLines: 9, borderDecoration: TextFormFieldStyleHelper.fillOnPrimary, filled: true, fillColor: theme.colorScheme.onPrimary), SizedBox(height: 32.v), CustomElevatedButton(text: "lbl_send".tr, margin: EdgeInsets.symmetric(horizontal: 32.h)), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 12.v, bottom: 12.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarTitle(text: "lbl_write_a_review".tr)); } 
/// Section Widget
Widget _buildRatingColumn() { return Container(width: 327.h, decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Padding(padding: EdgeInsets.only(right: 61.h), child: CustomTextFormField(controller: controller.ratingController, hintText: "lbl_rating".tr, contentPadding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 5.v), borderDecoration: TextFormFieldStyleHelper.fillPrimary, filled: true, fillColor: theme.colorScheme.primary))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
