import 'controller/verification_controller.dart';import 'package:flutter/material.dart';import 'package:yasir_s_application3/core/app_export.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:yasir_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:yasir_s_application3/widgets/custom_elevated_button.dart';import 'package:yasir_s_application3/widgets/custom_pin_code_text_field.dart';class VerificationScreen extends GetWidget<VerificationController> {const VerificationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 32.h, vertical: 17.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_verification".tr, style: CustomTextStyles.headlineSmallIntegralCFBold), SizedBox(height: 17.v), SizedBox(width: 196.h, child: Text("msg_check_your_email".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallIntegralCF.copyWith(height: 1.60))), SizedBox(height: 38.v), Obx(() => CustomPinCodeTextField(context: Get.context!, controller: controller.otpController.value, onChanged: (value) {})), Spacer(flex: 26), Align(alignment: Alignment.center, child: Text("msg_did_you_receive".tr, style: CustomTextStyles.labelLargePrimary)), SizedBox(height: 29.v), CustomElevatedButton(text: "lbl_verify".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), alignment: Alignment.center), Spacer(flex: 73)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.fromLTRB(24.h, 12.v, 319.h, 12.v), onTap: () {onTapArrowLeft();})); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
