import 'controller/edit_card_controller.dart';import 'package:flutter/material.dart';import 'package:yasir_s_application3/core/app_export.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:yasir_s_application3/widgets/app_bar/appbar_title.dart';import 'package:yasir_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:yasir_s_application3/widgets/custom_elevated_button.dart';class EditCardScreen extends GetWidget<EditCardController> {const EditCardScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 24.v), child: Column(children: [_buildCard(), SizedBox(height: 21.v), _buildLabel(), SizedBox(height: 16.v), Divider(indent: 12.h), SizedBox(height: 5.v)])), bottomNavigationBar: _buildSave())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 12.v, bottom: 12.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarTitle(text: "lbl_edit_card".tr)); } 
/// Section Widget
Widget _buildCard() { return SizedBox(height: 176.v, width: 327.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage176x327, height: 176.v, width: 327.h, radius: BorderRadius.circular(16.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 16.h, right: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgVisa, height: 24.v, width: 77.h, alignment: Alignment.centerRight), SizedBox(height: 59.v), Text("lbl_megan_susan".tr, style: CustomTextStyles.bodyMedium15), Text("msg_5124_3256_6589_2048".tr, style: CustomTextStyles.titleLargeOpenSansSemiBold)])))])); } 
/// Section Widget
Widget _buildLabel() { return SizedBox(height: 322.v, width: 332.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(right: 5.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildInput(), SizedBox(height: 20.v), _buildInput(), SizedBox(height: 20.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: _buildInput1()), _buildInput1()]), SizedBox(height: 78.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 5.h), child: Text("lbl_delete_card".tr, style: CustomTextStyles.titleMediumRedA400)))]))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 42.v), child: SizedBox(width: 327.h, child: Divider())))])); } 
/// Section Widget
Widget _buildSave() { return CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.only(left: 56.h, right: 56.h, bottom: 32.v)); } 
/// Common widget
Widget _buildInput() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_card_number".tr, style: CustomTextStyles.bodySmallPrimary)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_5124_3256_6589".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 14.v), Divider()]); } 
/// Common widget
Widget _buildInput1() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_cvc".tr, style: CustomTextStyles.bodySmallPrimary)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_696".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 14.v), SizedBox(width: 153.h, child: Divider())]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
