import 'controller/workout_plan_detail_controller.dart';import 'package:flutter/material.dart';import 'package:yasir_s_application3/core/app_export.dart';import 'package:yasir_s_application3/widgets/custom_drop_down.dart';import 'package:yasir_s_application3/widgets/custom_elevated_button.dart';import 'package:yasir_s_application3/widgets/custom_text_form_field.dart';class WorkoutPlanDetailScreen extends GetWidget<WorkoutPlanDetailController> {const WorkoutPlanDetailScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(height: mediaQueryData.size.height, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: SizedBox(height: mediaQueryData.size.height, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [_buildFortySixStack(), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 33.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.customBorderTL32), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildTimeStack(), SizedBox(height: 31.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 26.v, 16.h, 26.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "msg_simple_warm_up_exercises".tr, items: controller.workoutPlanDetailModelObj.value.dropdownItemList!.value, prefix: Container(margin: EdgeInsets.only(right: 16.h), decoration: BoxDecoration(borderRadius: BorderRadius.horizontal(left: Radius.circular(12.h))), child: CustomImageView(imagePath: ImageConstant.imgImage76x82, height: 76.v, width: 82.h)), prefixConstraints: BoxConstraints(maxHeight: 76.v), onChanged: (value) {controller.onSelected(value);}), SizedBox(height: 16.v), _buildTitleRow(), SizedBox(height: 22.v)])))]))), _buildButtonColumn()])))); } 
/// Section Widget
Widget _buildFortySixStack() { return Align(alignment: Alignment.topCenter, child: SizedBox(height: 338.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgImage338x375, height: 338.v, width: 375.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgArrowLeftOnerror, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.topLeft, margin: EdgeInsets.only(left: 24.h, top: 56.v), onTap: () {onTapImgArrowLeft();})]))); } 
/// Section Widget
Widget _buildTimeStack() { return Align(alignment: Alignment.centerLeft, child: SizedBox(height: 267.v, width: 307.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(top: 79.v), child: Row(children: [CustomTextFormField(width: 86.h, controller: controller.timeController, hintText: "lbl_60_min".tr, hintStyle: theme.textTheme.bodyMedium!, prefix: Container(margin: EdgeInsets.fromLTRB(5.h, 5.v, 6.h, 5.v), child: CustomImageView(imagePath: ImageConstant.imgPlayWhiteA700, height: 19.adaptSize, width: 19.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 29.v), contentPadding: EdgeInsets.only(top: 5.v, right: 14.h, bottom: 5.v), borderDecoration: TextFormFieldStyleHelper.fillOnPrimary, filled: true, fillColor: theme.colorScheme.onPrimary), Padding(padding: EdgeInsets.only(left: 17.h), child: CustomTextFormField(width: 89.h, controller: controller.calCounterController, hintText: "lbl_350_cal".tr, hintStyle: theme.textTheme.bodyMedium!, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(5.h, 5.v, 6.h, 5.v), child: CustomImageView(imagePath: ImageConstant.imgFlame, height: 19.adaptSize, width: 19.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 29.v), contentPadding: EdgeInsets.only(top: 5.v, right: 14.h, bottom: 5.v), borderDecoration: TextFormFieldStyleHelper.fillOnPrimary, filled: true, fillColor: theme.colorScheme.onPrimary))]))), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_day_01_warm_up".tr, style: CustomTextStyles.titleLargeOpenSansSemiBold), SizedBox(height: 4.v), Text("msg_04_workouts_for2".tr, style: CustomTextStyles.bodyMediumPrimary_1), SizedBox(height: 90.v), SizedBox(width: 307.h, child: Text("msg_want_your_body_to".tr, maxLines: 6, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMedium15.copyWith(height: 1.40)))]))]))); } 
/// Section Widget
Widget _buildTitleRow() { return Container(decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgImage9, height: 76.v, width: 82.h, radius: BorderRadius.horizontal(left: Radius.circular(12.h))), Padding(padding: EdgeInsets.only(left: 16.h, top: 9.v, bottom: 9.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 122.h, child: Text("msg_stability_training".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall!.copyWith(height: 1.20))), SizedBox(height: 2.v), Text("lbl_0_30".tr, style: CustomTextStyles.bodyMediumPrimary_1)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 26.v, right: 16.h, bottom: 26.v))])); } 
/// Section Widget
Widget _buildButtonColumn() { return Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 55.h, vertical: 31.v), decoration: AppDecoration.gradientOnPrimaryContainerToOnPrimaryContainer1, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 77.v), CustomElevatedButton(text: "lbl_start_workout".tr)]))); } 

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); } 
 }
