import 'controller/profile_controller.dart';import 'package:flutter/material.dart';import 'package:yasir_s_application3/core/app_export.dart';import 'package:yasir_s_application3/widgets/custom_text_form_field.dart';class ProfileScreen extends GetWidget<ProfileController> {const ProfileScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 43.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 13.v), CustomImageView(imagePath: ImageConstant.imgArrowLeftOnprimary, height: 32.adaptSize, width: 32.adaptSize, onTap: () {onTapImgArrowLeft();}), SizedBox(height: 32.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 38.h), child: Row(children: [Container(height: 104.adaptSize, width: 104.adaptSize, margin: EdgeInsets.only(bottom: 2.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 104.adaptSize, width: 104.adaptSize, decoration: AppDecoration.outlineOnPrimary3.copyWith(borderRadius: BorderRadiusStyle.circleBorder52), child: CustomImageView(imagePath: ImageConstant.imgGroup284, height: 104.adaptSize, width: 104.adaptSize, alignment: Alignment.center))), CustomImageView(imagePath: ImageConstant.img5980x80, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(40.h), alignment: Alignment.center)])), Spacer(), SizedBox(height: 106.v, child: VerticalDivider(width: 1.h, thickness: 1.v, indent: 3.h)), Padding(padding: EdgeInsets.only(left: 22.h, top: 37.v, bottom: 30.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_joined".tr, style: CustomTextStyles.bodySmallPrimaryContainer), SizedBox(height: 2.v), Text("lbl_2_month_ago".tr, style: theme.textTheme.titleSmall)]))])), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_sarah".tr, style: CustomTextStyles.headlineLargeBold)), SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_wegan".tr, style: theme.textTheme.headlineLarge)), SizedBox(height: 21.v), SizedBox(height: 426.v, width: 327.h, child: Stack(alignment: Alignment.center, children: [_buildPremiumLink(), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: Column(mainAxisSize: MainAxisSize.min, children: [Divider(), SizedBox(height: 17.v), _buildProfileList(), SizedBox(height: 19.v), _buildProfileList(), SizedBox(height: 19.v), _buildProfileList(), SizedBox(height: 180.v), Divider(), SizedBox(height: 20.v), CustomTextFormField(controller: controller.signOutController, hintText: "lbl_sign_out".tr, hintStyle: CustomTextStyles.titleMediumRedA40001, textInputAction: TextInputAction.done)])))]))])))); } 
/// Section Widget
Widget _buildPremiumLink() { return Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(top: 233.v, bottom: 110.v), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 7.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(left: 2.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 37.h, padding: EdgeInsets.symmetric(horizontal: 4.h, vertical: 1.v), decoration: AppDecoration.fillRedA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_pro".tr, style: theme.textTheme.labelMedium)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("msg_upgrade_to_premium".tr, style: theme.textTheme.titleMedium)), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("msg_this_subscription".tr, style: theme.textTheme.bodyMedium))])), CustomImageView(imagePath: ImageConstant.imgArrowRightWhiteA700, height: 32.adaptSize, width: 32.adaptSize, margin: EdgeInsets.only(top: 18.v, bottom: 17.v))]))); } 
/// Common widget
Widget _buildProfileList() { return Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("lbl_privacy_policy".tr, style: theme.textTheme.titleSmall)), CustomImageView(imagePath: ImageConstant.imgArrowRightGray300, height: 24.adaptSize, width: 24.adaptSize)]), SizedBox(height: 17.v), Divider()]); } 

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); } 
 }
